project:
  type: website
  output-dir: docs

website:
  title: "ujjal"
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
        #index.qmd
      - text: "About Me"
        file: about.qmd





 
  page-footer: 
    left: "Copyright 2025, ujjal" 
    right: 
      - icon: github
        href: https://github.com/ujjalkumarmaity/
      - icon: linkedin
        href: https://www.linkedin.com/in/ujjalkumar/
      - icon: twitter 
        href: https://twitter.com/ 
      - icon: youtube 
        href: https://www.youtube.com/channel/UCypg_Mb5eGxA0S5P4_l4uKg/ 

format:
  html:
    theme: 
      light: flatly
      dark: darkly
    toc: false
    page-layout: article # removes sidebar

  # html:
  #   theme: cosmo
  #   css: styles.css
  #   toc: true
  #   sidebar: false


# ---
# title: "Post With Code"
# description: "Post description"
# author: "Fizz McPhee"
# date: "5/22/2021"
# categories:
#   - news
#   - code
#   - analysis
# ---


# Steps to deploy
# run - quarto preview
# then commit and push