project:
  type: website

# website:
#   back-to-top-navigation: true
#   title: "blogs"
#   # navbar:
#   #   left:
#   #     - href: index.qmd
#   #       text: Home
#   #     - about.qmd
#   sidebar:
#     style : "docked"
#     search : true
#     contents :
#       - section: "sastai"
#         contents:
#           - herf: ml/2021-12-28-logistic-regression-from-scratch.ipnyb
#           - herf: ml/2022-12-28-Mean-Median-Imputation.ipnyb
#       - section: "fastai"
website:
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Basics"
        contents:
          - index.qmd

  page-footer: 
    left: "Copyright 2021, ujjal" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



