project:
  type: website
  output-dir: docs
# website:
#   back-to-top-navigation: true
#   title: "blogs"
#   # navbar:
#   #   left:
#   #     - href: index.qmd
#   #       text: Home
#   #     - about.qmd
#   sidebar:
#     style : "docked"
#     search : true
#     contents :
#       - section: "sastai"
#         contents:
#           - herf: ml/2021-12-28-logistic-regression-from-scratch.ipnyb
#           - herf: ml/2022-12-28-Mean-Median-Imputation.ipnyb
#       - section: "fastai"
website:
  title: "ujjal"
  navbar:
    background: primary
    search: true
    right:
      - text: "Home"
        file: index.qmd
        #index.qmd
      - text: "About Me"
        file: about.qmd

  sidebar:
    style: "docked"
    search: true
    collapse-level: 0
    contents:
      # - section: "Research-Paper-Implementation"
      #   contents:
      #     - index.qmd
      - section: "ML"
        contents:
          - ml/logistic-regression-from-scratch/logistic-regression-from-scratch.qmd




      - section: "NLP"
        contents:
          - nlp/rnn/RNN.qmd
          - section: "Resume Parsing"
            contents:
              - nlp/spacy.qmd       
          - nlp/spacy.qmd                       
      - section: "Python"
        contents:
          - python/python_advance.qmd
      # - section: "SQL"
      #   contents:
      #     - python/about1.qmd
      # - section: "MongoSB"
      #   contents:
      #     - python/about1.qmd

  page-footer: 
    # left: "Copyright 2021, ujjal" 
    right: 
      - icon: github
        href: https://github.com/ujjalkumarmaity/
      - icon: linkedin
        href: https://www.linkedin.com/in/ujjalkumar/
      - icon: twitter 
        href: https://twitter.com/ 
      - icon: youtube 
        href: https://www.youtube.com/channel/UCypg_Mb5eGxA0S5P4_l4uKg/ 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



# ---
# title: "Post With Code"
# description: "Post description"
# author: "Fizz McPhee"
# date: "5/22/2021"
# categories:
#   - news
#   - code
#   - analysis
# ---